services:
  - type: web
    name: mistral-chat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python cyberpsycho/app.py
    plan: free
envVars:
  - key: MODEL_NAME
    value: TheBloke/Mistral-7B-Instruct-v0.1-GGUF
